//! Lists every block's `spec/` directory so the binary can carry the specs
//! beside the modules they check.
//!
//! The modules themselves are embedded by hand in `src/host.rs`
//! (`EMBEDDED_BLOCKS` / `EMBEDDED_LIBS`): a `require` name is a decision, and a
//! list someone wrote is the right place for one. A spec is not: it belongs to
//! whichever module's `spec/` it sits in, its name is its file name, and a new
//! spec file should become part of the module without anyone remembering to
//! register it — which is exactly what an `include_str!` list kept by hand
//! forgets. So this script walks `blocks/<name>/spec/*.lua` and
//! `blocks/lib/<name>/spec/*.lua` and writes the list to `OUT_DIR`, and
//! `src/embedded.rs` includes it.
//!
//! `agent-block vendor <name>` is the consumer: a vendored module is written
//! with its `spec/`, so the project's copy can be checked by the same specs
//! that check the embedded one (`lua-spec-runner --project <dir>`).

use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let blocks = manifest.join("blocks");
    // A directory here means "rerun when anything under it changes", which is
    // what a new spec file is.
    println!("cargo:rerun-if-changed={}", blocks.display());

    let mut specs: Vec<(String, String, PathBuf)> = Vec::new();
    for parent in [blocks.clone(), blocks.join("lib")] {
        for module in dirs_in(&parent) {
            let name = module
                .file_name()
                .and_then(|n| n.to_str())
                .expect("utf-8 directory name")
                .to_string();
            if name == "lib" {
                continue; // `blocks/lib` is the second parent, not a module.
            }
            let spec = module.join("spec");
            if !spec.is_dir() {
                continue;
            }
            for file in files_in(&spec) {
                if file.extension().and_then(|e| e.to_str()) != Some("lua") {
                    continue;
                }
                let file_name = file
                    .file_name()
                    .and_then(|n| n.to_str())
                    .expect("utf-8 file name")
                    .to_string();
                specs.push((name.clone(), file_name, file));
            }
        }
    }
    specs.sort();

    let mut out = String::from(
        "/// Every `spec/*.lua` under a block or a module, as `(module, file name, source)`.\n\
         /// Generated by `build.rs` from the tree; see there for why it is not a hand list.\n\
         pub(crate) const EMBEDDED_SPECS: &[(&str, &str, &str)] = &[\n",
    );
    for (module, file, path) in &specs {
        out.push_str(&format!(
            "    ({module:?}, {file:?}, include_str!({:?})),\n",
            path.display().to_string()
        ));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("embedded_specs.rs");
    std::fs::write(&dest, out).expect("write embedded_specs.rs");
}

/// The sub-directories of `dir`, sorted, or nothing if it is not a directory.
fn dirs_in(dir: &Path) -> Vec<PathBuf> {
    let mut v: Vec<PathBuf> = std::fs::read_dir(dir)
        .into_iter()
        .flatten()
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.is_dir())
        .collect();
    v.sort();
    v
}

/// The files directly in `dir`, sorted.
fn files_in(dir: &Path) -> Vec<PathBuf> {
    let mut v: Vec<PathBuf> = std::fs::read_dir(dir)
        .into_iter()
        .flatten()
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.is_file())
        .collect();
    v.sort();
    v
}
