-- Generated by agent-block-core from the argument and return types of
-- `bridge/knl.rs` (schema-bridge -> lshape): what the host embeds as
-- `knl_types`, built at its start. The copy in the tree is for the
-- runners that have no host, and a test holds it to the generator, so
-- there is nothing here to edit.
local T = require("lshape").t

local M = {}

M.SessionId = T.string:describe("SessionId")

M.ScopeId = T.string:describe("ScopeId")

M.Owner = T.string:describe("Owner")

M.BeatId = T.string:describe("BeatId")

M.Seq = T.integer:describe("Seq")

M.Count = T.integer:describe("Count")

M.Amount = T.integer:describe("Amount")

M.Remaining = T.integer:is_optional()

M.Exhausted = T.boolean:describe("Exhausted")

M.Sql = T.string:describe("Sql")

M.CloseReason = T.string:describe("CloseReason")

M.CloseDetail = T.string:describe("CloseDetail")

M.Raised = T.any:describe("Raised")

M.ViewName = T.one_of({ "tail" })

M.ViewOpts = T.shape({
    n = T.integer:is_optional(),
}, { open = false })

M.OpenOpts = T.shape({
    owner = T.string:is_optional(),
    budget = T.any_of({ T.shape({
        amount = T.integer,
        tag = T.string:is_optional(),
        desc = T.string:is_optional(),
    }), T.shape({
        from_parent = T.integer,
        tag = T.string:is_optional(),
    }) }):is_optional(),
    store = T.any_of({ T.one_of({ "mem" }), T.shape({
        sqlite = T.string,
    }) }):is_optional(),
    meta = T.map_of(T.string, T.any_of({ T.string, T.number, T.boolean })):is_optional(),
    parent = T.any:is_optional(),
})

M.ResumeOpts = T.shape({
    store = T.any_of({ T.one_of({ "mem" }), T.shape({
        sqlite = T.string,
    }) }):is_optional(),
    session = T.string,
    budget = T.any_of({ T.shape({
        amount = T.integer,
        tag = T.string:is_optional(),
        desc = T.string:is_optional(),
    }), T.shape({
        from_parent = T.integer,
        tag = T.string:is_optional(),
    }) }):is_optional(),
})

M.AppendEvent = T.shape({
    kind = T.string,
    meta = T.map_of(T.string, T.any_of({ T.string, T.number, T.boolean })):is_optional(),
    data = T.any:is_optional(),
})

M.EventsResult = T.tuple({ T.array_of(T.shape({
    kind = T.string,
    seq = T.integer,
    epoch_ms = T.integer,
    _schema_version = T.integer,
    meta = T.map_of(T.string, T.any_of({ T.string, T.number, T.boolean })):is_optional(),
    data = T.any,
})), T.boolean })

M.QueryParams = T.any_of({ T.array_of(T.any), T.map_of(T.string, T.any) })

M.QueryOpts = T.shape({
    sessions = T.array_of(T.string):is_optional(),
    timeout_ms = T.integer:is_optional(),
    limit = T.integer:is_optional(),
}, { open = false })

M.QueryResult = T.tuple({ T.array_of(T.any), T.boolean })

M.ErrorTable = T.shape({
    kind = T.string:is_optional(),
    method = T.string:is_optional(),
    retryable = T.boolean,
    message = T.string,
})

M.ApiReport = T.shape({
    session = T.array_of(T.shape({
        name = T.string,
        doc = T.string,
    })),
    module = T.array_of(T.shape({
        name = T.string,
        doc = T.string,
    })),
    errors = T.array_of(T.string),
    schema = T.shape({
        table = T.string,
        columns = T.array_of(T.shape({
            name = T.string,
            type = T.string,
            pk = T.boolean,
        })),
    }),
    fields = T.shape({
        amount = T.string,
        tag = T.string,
        desc = T.string,
        remaining = T.string,
        scope_id = T.string,
        owner = T.string,
        parent = T.string,
        child = T.string,
        reason = T.string,
        detail = T.string,
        open_children = T.string,
    }),
    types = T.string,
})

return M
